# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41bcecf7be61c8b713266c594f3fe1ad84e8eb757a1a2335a03c311b05c6a72ae8281f9cb14911892f9efdf72f048809988e40622223a09a928d1952ad2fa42d

test:
  secret_key_base: d7b0d30bbe290199002c5ac3da36977a1ec7720afc2ac11573f70e6f87151555f5bf502d6f96880edc4fb7ea42bf657a1a040d4c208cd06083c874e88c7436e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
